# See http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# spring.thymeleaf.cache=false
# spring.main.show-banner=false
# logging.level.jdbc=OFF
# logging.level.jdbc.sqltiming=DEBUG
# logging.level.jdbc.resultsettable=DEBUG

spring.datasource.url=jdbc:postgresql://localhost:5433/erp_system
spring.datasource.username=postgres
spring.datasource.password=Query@2026

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080

logging.level.org.springframework=INFO
spring.main.allow-bean-definition-overriding=true
spring.jpa.hibernate.ddl-auto=validate

logging.level.jdbc=DEBUG
logging.level.jdbc.sqlonly=DEBUG
logging.level.jdbc.sqltiming=DEBUG
logging.level.jdbc.audit=DEBUG
logging.level.jdbc.resultset=DEBUG
logging.level.jdbc.connection=DEBUG
